# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-11 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0004_blocked_number_sms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocked_poster',
            name='ip',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blocked_poster',
            name='name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
