# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-27 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0005_auto_20171211_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('poster', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Advertentie',
                'verbose_name_plural': 'Advertenties',
            },
        ),
        migrations.AlterModelOptions(
            name='blocked_number',
            options={'verbose_name': 'Blocked Number', 'verbose_name_plural': 'Blocked Numbers'},
        ),
        migrations.AlterModelOptions(
            name='blocked_poster',
            options={'verbose_name': 'Blocked Poster', 'verbose_name_plural': 'Blocked Posters'},
        ),
    ]
