# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-27 21:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0006_auto_20171227_2119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={},
        ),
    ]
