# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-30 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0007_auto_20171227_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='is_ad',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='picture',
            name='is_ad',
            field=models.BooleanField(default=False),
        ),
    ]
