# Generated by Django 2.1.1 on 2018-10-04 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0008_auto_20171230_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='sms',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
